const CONFIG = {
    introTitle: 'Trang ơi',
    introDesc: `Em có đang rảnh không ?`,
    btnIntro: 'Rảnh thì nhấn đây nha',
    title: 'Anh muốn hỏi em là:',
    desc: 'Em có yêu anh khônggggg?',
    btnYes: 'Có ạ',
    btnNo: 'Đéo ',
    question:'Tại sao em yêu anh nhờ???',
    btnReply: 'Trả lời',
    reply: 'Em không cần trả lời đâu anh biết mà<33333333',
    mess: 'HiHi',
    messDesc: 'Yêu❤ ...',
    btnAccept: 'Send to me',
    messLink: 'http://www.facebook.com/messages/t/100006317044070' //link mess
